title: Anna Harvey # your name (or website title) here
logo: "/images/Screen%20Shot%202021-05-05%20at%2011.11.32%20AM.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)

  <a href="https://www.linkedin.com/in/annaharvey23/">LinkedIn</a> 
  <br>
  <a href="/pdf/Anna%20Harvey%20Resume.pdf/" class="btn btn--info">Resume</a>  
  <br>
  <a href="https://bowen.finance/" class="btn btn--info">Portfolio</a>  
  <br>
  <a href="https://github.com/annakharv46/">GitHub</a>  
  <br>
  
theme: jekyll-theme-minimal
