title: Anna Harvey # your name (or website title) here
logo: "/images/Anna Vertical.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)

  <a href="https://www.linkedin.com/in/annaharvey23/">LinkedIn</a> 
  <br>
  <a href="/pdf/Anna%20Harvey%20Resume.pdf?raw=true/">Resume</a> 
  <br>
  <a href="https://github.com/annakharv46/">GitHub</a>  
  <br>
  
theme: jekyll-theme-minimal
